from typing import List, Dict, Any
from datasets import Dataset

from clemcore.backends import Model

from playpen.envs.branching_env import GameBranchingEnv, GameTree, ResponseTreeNode


class ConversationLike:

    def to_conversational_dataset(self, perspective: Model) -> Dataset:
        """
        Converts the data collected in the buffer into a dataset where each row represents a conversation.

        A conversation is basically a dict where the "messages" entry points to a list of dicts where each
        of these contain alternating entries of "role" (assistant or user) and "content" depending on the perspective.
        For example:

        {"messages" = [
            {"role": "user", "content": "Hello, how are you?"},\n
            {"role": "assistant", "content": "I'm doing great. How can I help you today?"},\n
            {"role": "user", "content": "I'd like to show off how chat templating works!"}\n
            ]}

        See also https://huggingface.co/docs/trl/dataset_formats#conversational
        Args:
            perspective: to take in the dataset as specified by the given model
        Returns: the Dataset
        """
        pass


class EpisodeBuffer(ConversationLike):
    """ Buffer to collect the full episode trajectories generated by a session of game play"""

    def __init__(self):
        self.episodes: List[List[Dict[str, Any]]] = [[]]
        self.current_episode: int = 0

    def add_step(self, context, response, done, info):
        """Append a step to the current episode."""
        self.episodes[self.current_episode].append({
            "context": context,
            "response": response,
            "done": done,
            "info": info
        })

    def next_episode(self):
        if self.episodes[self.current_episode]:  # only if current episode not empty
            self.episodes.append([])
            self.current_episode += 1

    def reset(self):
        """Clear all stored episodes."""
        self.episodes: List[List[Dict[str, Any]]] = [[]]
        self.current_episode: int = 0

    def __iter__(self):
        return iter(self.episodes)


class BranchingRolloutBuffer:
    """ This buffer can collect the trajectories generated by the branching env """

    def __init__(self, game_env: GameBranchingEnv):
        assert isinstance(game_env, GameBranchingEnv), "TreeRolloutBuffer can only be used with GameBranchingEnv"
        super().__init__(game_env)
        self.forest: List[GameTree] = None
        self.reset()

    def on_done(self):
        active_tree = self.game_env.get_active_tree()
        self.forest.append(active_tree)

    def reset(self):
        self.forest = []

    def to_conversational_dataset(self, perspective: Model) -> Dataset:
        def recursive_add_to(_messages: List[Dict], node: ResponseTreeNode):
            # only collect for given conversational perspective
            player_model = node.unwrap().master.current_player.model
            if perspective is player_model:
                # we reverse later
                _messages.append(dict(role="assistant", content=node.response))
                _messages.append(node.context)
            if isinstance(node.parent, ResponseTreeNode):
                recursive_add_to(_messages, node.parent)
            return _messages

        dataset = []
        for active_tree in self.forest:
            for leave in active_tree.find_leaves():
                messages = recursive_add_to([], leave)
                messages.reverse()
                dataset.append(dict(messages=messages, reward=leave.info["episode_score"]))
        return Dataset.from_list(dataset)
