import math
from collections import defaultdict
from dataclasses import dataclass
from threading import Lock
from typing import List, Dict, Any, Protocol
from datasets import Dataset

from clemcore.clemgame import GameStep, GameSnapshot


class PreferenceLike(Protocol):

    def to_preference_dataset(self, player_name: str, data_format="conversational") -> Dataset:
        """
        Transform the rollout buffer to a preference dataset for, e.g., DPO learning.

        # Standard format
        preference_example = {"prompt": "The sky is", "chosen": " blue.", "rejected": " green."}

        # Conversational format
        preference_example = {"prompt": [{"role": "user", "content": "What color is the sky?"}],
                              "chosen": [{"role": "assistant", "content": "It is blue."}],
                              "rejected": [{"role": "assistant", "content": "It is green."}]}

        Args:
            player_name: the perspective of the player given by name on the conversation
            data_format: conversational or standard

        Returns: A preference dataset as described in https://huggingface.co/docs/trl/dataset_formats#preference
        """
        return Dataset.from_list([])


class ConversationLike(Protocol):

    def to_conversational_dataset(self, player_name: str) -> Dataset:
        """
        Converts the data collected in the buffer into a dataset where each row represents a conversation.

        A conversation is basically a dict where the "messages" entry points to a list of dicts where each
        of these contain alternating entries of "role" (assistant or user) and "content" depending on the perspective.
        For example:

        {"messages" = [
            {"role": "user", "content": "Hello, how are you?"},\n
            {"role": "assistant", "content": "I'm doing great. How can I help you today?"},\n
            {"role": "user", "content": "I'd like to show off how chat templating works!"}\n
            ]}

        See also https://huggingface.co/docs/trl/dataset_formats#conversational
        Args:
            player_name: the perspective of the player given by name on the conversation
        Returns: the Dataset
        """
        return Dataset.from_list([])


class EpisodeBuffer(ConversationLike):
    """ Buffer to collect the full episode trajectories generated by a session of game play"""

    def __init__(self):
        self.episodes: list[list[GameStep]] = [[]]
        self.current_episode: int = 0

    def add_step(self, game_step: GameStep):
        """Append a step to the current episode."""
        self.episodes[self.current_episode].append(game_step)

    def next_episode(self):
        if self.episodes[self.current_episode]:  # only if current episode not empty
            self.episodes.append([])
            self.current_episode += 1

    def reset(self):
        """Clear all stored episodes."""
        self.episodes = [[]]
        self.current_episode = 0

    def __iter__(self):
        return iter(self.episodes)


@dataclass
class BranchingPoint:
    """A snapshot of a trajectory up to and including the point where it diverged
    from its siblings. Siblings share the same snapshot and the same
    prompt, but differ in their response and episode_score.

    Note that trajectory is a SUB-trajectory — it is sliced from the full episode
    trajectory at the divergence point, so it only contains steps up to and including
    the diverging response. The full episode trajectory is not stored here.
    """
    game_snapshot: GameSnapshot
    trajectory: list[GameStep]  # sub-trajectory up to and including the diverging response
    episode_score: float

    @property
    def prompt(self) -> list[GameStep]:
        """Shared context up to the divergence point — identical across siblings."""
        return self.trajectory[:-1]

    @property
    def diverging_step(self) -> GameStep:
        """The diverging response — differs across siblings with the same snapshot origin."""
        return self.trajectory[-1]


class BranchingEpisodeBuffer(ConversationLike, PreferenceLike):
    """Buffer to collect all branching points generated by a session of game play over multiple instances.

    This buffer is SHARED across all branches during a BranchingRunner run — its __deepcopy__
    returns self so that all branches write to the same buffer. Thread safety is ensured
    via a Lock on add_branching_point.

    Each entry in the buffer is a BranchingPoint — a sub-trajectory sliced at a divergence
    point in the episode tree. A single branch (leaf) contributes one BranchingPoint per
    branching point it passed through, so a branch that passed through 3 branching points
    adds 3 entries to the buffer, each with a different sub-trajectory length.

    Siblings — branches that share the same snapshot origin — can then be compared in
    to_preference_dataset to form chosen/rejected pairs for DPO training.

    Note on to_conversational_dataset:
        Since BranchingPoints only store sub-trajectories (up to the divergence point),
        to_conversational_dataset returns partial episodes, not full ones. If full episode
        trajectories are needed, consider using a separate callback alongside this one.
    """

    def __init__(self):
        self._branching_points: List[BranchingPoint] = []
        self._trajectories: List[tuple[list[GameStep], float]] = []  # (full_trajectory, episode_score)
        self._lock = Lock()

    def __deepcopy__(self, memo):
        # Always return the same instance - this buffer must be shared across all branches
        # so that all branches contribute their branching points to the same collection.
        return self

    def add_branching_point(
            self,
            game_snapshot: GameSnapshot,
            branch_turn: int,
            trajectory: list[GameStep],
            episode_score: float
    ):
        """Add a branching point to the buffer.

        Slices the full trajectory at branch_turn+1 so only the relevant sub-trajectory
        is stored. Thread-safe via internal lock.

        Args:
            game_snapshot: Identifies the branching point — shared across siblings
            branch_turn: Index into the full trajectory where divergence occurred
            trajectory: The full episode trajectory — will be sliced, not stored in full
            episode_score: The final outcome score for this branch
        """
        sub_trajectory = trajectory[:branch_turn + 1]
        with self._lock:
            self._branching_points.append(BranchingPoint(game_snapshot, sub_trajectory, episode_score))
            # Store full trajectory only once per branch (identified by the last marker)
            # We deduplicate by checking if this exact trajectory is already stored
            if not any(t is trajectory for t, _ in self._trajectories):
                self._trajectories.append((trajectory, episode_score))

    def reset(self):
        self._branching_points = []
        self._trajectories = []

    def to_conversational_dataset(self, player_name: str) -> Dataset:
        """Convert collected branching points to a conversational dataset.

        Args:
            player_name: the perspective of the player given by name on the conversation
        """
        dataset = []
        for trajectory, episode_score in self._trajectories:
            messages = []
            for step in trajectory:
                if step.player_name == player_name:
                    messages.append(step.context)  # {"role": "user", ...} - GM prompt/mediator message
                    messages.append({"role": "assistant", "content": step.response})
            dataset.append({"messages": messages})
        return Dataset.from_list(dataset)

    def to_preference_dataset(
            self,
            player_name: str,
            data_format="conversational",
            require_different_scores: bool = True
    ) -> Dataset:
        """Convert collected branching points to a preference dataset for DPO training.

        Groups branching points by snapshot origin to find siblings — branches that
        diverged from the same point. Within each sibling group, ranks by episode_score
        and forms chosen/rejected pairs. Skips groups where all siblings have the same
        score, as these provide no preference signal.

        Note:
            The outcome difference might be driven by later turns, not the turn 1 response itself.
            The turn 1 preference signal is "noisier" because there are many confounding factors downstream.
            This is actually a known issue in RLHF/DPO literature — preference pairs are most reliable
            when the divergence point is close to the outcome. Some approaches weight pairs by
            "proximity to outcome" or only use the last branching point.

        Args:
            player_name: The player whose responses form the chosen/rejected pairs
            data_format: "conversational" (default) or "standard" as per HuggingFace TRL format
                See: https://huggingface.co/docs/trl/dataset_formats#preference
        """
        if data_format != "conversational":
            raise NotImplementedError("Only conversational format is implemented for now.")

        groups = defaultdict(list)
        for branching_point in self._branching_points:
            groups[branching_point.game_snapshot.origin].append(branching_point)

        pairs = []
        for siblings in groups.values():
            if len(siblings) < 2:
                continue
            ranked = sorted(siblings, key=lambda s: s.episode_score, reverse=True)
            chosen, rejected = ranked[0], ranked[-1]
            if require_different_scores and math.isclose(chosen.episode_score, rejected.episode_score, abs_tol=1e-6):
                continue

            # Build prompt from shared trajectory up to divergence point
            prompt = []
            for step in chosen.prompt:
                if step.player_name == player_name:
                    prompt.append(step.context)  # {"role": "user", ...} - GM prompt
                    prompt.append({"role": "assistant", "content": step.response})

            # Add the final GM message that prompted the diverging response
            prompt.append(chosen.diverging_step.context)

            pairs.append({
                "prompt": prompt,
                "chosen": [{"role": "assistant", "content": chosen.diverging_step.response}],
                "rejected": [{"role": "assistant", "content": rejected.diverging_step.response}],
            })
        return Dataset.from_list(pairs)
