from collections import defaultdict
from dataclasses import dataclass
from threading import Lock
from typing import List, Dict, Any, Protocol
from datasets import Dataset

from clemcore.backends import Model
from clemcore.clemgame import GameStep


class PreferenceLike(Protocol):

    def to_preference_dataset(self, perspective: Model, data_format="conversational") -> Dataset:
        """
        Transform the rollout buffer to a preference dataset for, e.g., DPO learning.

        # Standard format
        preference_example = {"prompt": "The sky is", "chosen": " blue.", "rejected": " green."}

        # Conversational format
        preference_example = {"prompt": [{"role": "user", "content": "What color is the sky?"}],
                              "chosen": [{"role": "assistant", "content": "It is blue."}],
                              "rejected": [{"role": "assistant", "content": "It is green."}]}

        :param perspective: of a model generating the responses
        :param data_format: conversational or standard
        :return: a preference dataset as described in https://huggingface.co/docs/trl/dataset_formats#preference
        """
        return Dataset.from_list([])


class ConversationLike(Protocol):

    def to_conversational_dataset(self, perspective: Model) -> Dataset:
        """
        Converts the data collected in the buffer into a dataset where each row represents a conversation.

        A conversation is basically a dict where the "messages" entry points to a list of dicts where each
        of these contain alternating entries of "role" (assistant or user) and "content" depending on the perspective.
        For example:

        {"messages" = [
            {"role": "user", "content": "Hello, how are you?"},\n
            {"role": "assistant", "content": "I'm doing great. How can I help you today?"},\n
            {"role": "user", "content": "I'd like to show off how chat templating works!"}\n
            ]}

        See also https://huggingface.co/docs/trl/dataset_formats#conversational
        Args:
            perspective: to take in the dataset as specified by the given model
        Returns: the Dataset
        """
        return Dataset.from_list([])


class EpisodeBuffer(ConversationLike):
    """ Buffer to collect the full episode trajectories generated by a session of game play"""

    def __init__(self):
        self.episodes: List[List[Dict[str, Any]]] = [[]]
        self.current_episode: int = 0

    def add_step(self, context, response, done, info):
        """Append a step to the current episode."""
        self.episodes[self.current_episode].append({
            "context": context,
            "response": response,
            "done": done,
            "info": info
        })

    def next_episode(self):
        if self.episodes[self.current_episode]:  # only if current episode not empty
            self.episodes.append([])
            self.current_episode += 1

    def reset(self):
        """Clear all stored episodes."""
        self.episodes: List[List[Dict[str, Any]]] = [[]]
        self.current_episode: int = 0

    def __iter__(self):
        return iter(self.episodes)


@dataclass
class BranchingPoint:
    """A snapshot of a trajectory up to and including the point where it diverged
    from its siblings. Siblings share the same branching_point_id and the same
    prompt, but differ in their response and episode_score.

    Note that trajectory is a SUB-trajectory — it is sliced from the full episode
    trajectory at the divergence point, so it only contains steps up to and including
    the diverging response. The full episode trajectory is not stored here.
    """
    branching_point_id: str
    trajectory: list[GameStep]  # sub-trajectory up to and including the diverging response
    episode_score: float

    @property
    def prompt(self) -> list[GameStep]:
        """Shared context up to the divergence point — identical across siblings."""
        return self.trajectory[:-1]

    @property
    def diverging_step(self) -> GameStep:
        """The diverging response — differs across siblings with the same branching_point_id."""
        return self.trajectory[-1]


class BranchingEpisodeBuffer(ConversationLike, PreferenceLike):
    """Buffer to collect all branching points generated by a session of game play over multiple instances.

    This buffer is SHARED across all branches during a BranchingRunner run — its __deepcopy__
    returns self so that all branches write to the same buffer. Thread safety is ensured
    via a Lock on add_branching_point.

    Each entry in the buffer is a BranchingPoint — a sub-trajectory sliced at a divergence
    point in the episode tree. A single branch (leaf) contributes one BranchingPoint per
    branching point it passed through, so a branch that passed through 3 branching points
    adds 3 entries to the buffer, each with a different sub-trajectory length.

    Siblings — branches that share the same branching_point_id — can then be compared in
    to_preference_dataset to form chosen/rejected pairs for DPO training.

    Note on to_conversational_dataset:
        Since BranchingPoints only store sub-trajectories (up to the divergence point),
        to_conversational_dataset returns partial episodes, not full ones. If full episode
        trajectories are needed, consider using a separate callback alongside this one.
    """

    def __init__(self):
        self._branching_points: List[BranchingPoint] = []
        self._trajectories: List[tuple[list[GameStep], float]] = []  # (full_trajectory, episode_score)
        self._lock = Lock()

    def __deepcopy__(self, memo):
        # Always return the same instance - this buffer must be shared across all branches
        # so that all branches contribute their branching points to the same collection.
        return self

    def add_branching_point(self, branching_point_id: str, branch_turn: int, trajectory: list[GameStep],
                            episode_score: float):
        """Add a branching point to the buffer.

        Slices the full trajectory at branch_turn+1 so only the relevant sub-trajectory
        is stored. Thread-safe via internal lock.

        Args:
            branching_point_id: Identifies the branching point — shared across siblings
            branch_turn: Index into the full trajectory where divergence occurred
            trajectory: The full episode trajectory — will be sliced, not stored in full
            episode_score: The final outcome score for this branch
        """
        sub_trajectory = trajectory[:branch_turn + 1]
        with self._lock:
            self._branching_points.append(BranchingPoint(branching_point_id, sub_trajectory, episode_score))
            # Store full trajectory only once per branch (identified by the last marker)
            # We deduplicate by checking if this exact trajectory is already stored
            if not any(t is trajectory for t, _ in self._trajectories):
                self._trajectories.append((trajectory, episode_score))

    def reset(self):
        self._branching_points = []
        self._trajectories = []

    def _to_messages(self, steps: list[GameStep], perspective: Model) -> list[dict]:
        """Convert a list of GameSteps to HuggingFace TRL messages from the given perspective.
        The perspective model is always 'assistant', all other models are 'user'.
        """
        messages = []
        for step in steps:
            if step.model_name == perspective.name:
                messages.append(step.context)  # already {"role": "user", "content": "..."}
                messages.append({"role": "assistant", "content": step.response})
            else:
                messages.append({**step.context, "role": "assistant"})
                messages.append({"role": "user", "content": step.response})
        return messages

    def to_conversational_dataset(self, perspective: Model) -> Dataset:
        """Convert collected branching points to a conversational dataset.

        Args:
            perspective: of the model whose responses are to be included in the dataset
        """
        dataset = []
        for trajectory, episode_score in self._trajectories:
            messages = self._to_messages(trajectory, perspective)
            dataset.append({"messages": messages})
        return Dataset.from_list(dataset)

    def to_preference_dataset(self, perspective: Model, data_format="conversational") -> Dataset:
        """Convert collected branching points to a preference dataset for DPO training.

        Groups branching points by branching_point_id to find siblings — branches that
        diverged from the same point. Within each sibling group, ranks by episode_score
        and forms chosen/rejected pairs. Skips groups where all siblings have the same
        score, as these provide no preference signal.

        Args:
            perspective: The model whose responses form the chosen/rejected pairs
            data_format: "conversational" (default) or "standard" as per HuggingFace TRL format
                See: https://huggingface.co/docs/trl/dataset_formats#preference
        """
        groups = defaultdict(list)
        for branching_point in self._branching_points:
            groups[branching_point.branching_point_id].append(branching_point)

        pairs = []
        for siblings in groups.values():
            if len(siblings) < 2:
                continue
            ranked = sorted(siblings, key=lambda s: s.episode_score, reverse=True)
            chosen, rejected = ranked[0], ranked[-1]
            if chosen.episode_score == rejected.episode_score:
                continue
            pairs.append({
                "prompt": self._to_messages(chosen.prompt, perspective),
                "chosen": [{"role": "assistant", "content": chosen.diverging_step.response}],
                "rejected": [{"role": "assistant", "content": rejected.diverging_step.response}],
            })
        return Dataset.from_list(pairs)
